
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Moshiur
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        error_lbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void onClick(JPanel panel)
    {
        panel.setBackground(new Color(255,255,255));
    }
    private void onLeaveClick(JPanel panel)
    {
        panel.setBackground(new Color(0,153,153));
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sidebar_admin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sidebar_student = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sidebar_teacher = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        centrePanel = new javax.swing.JPanel();
        cover = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        SignUp = new javax.swing.JPanel();
        signup_name = new javax.swing.JTextField();
        signup_email = new javax.swing.JTextField();
        signup_pass = new javax.swing.JPasswordField();
        signup_birth = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        signup_pass_check = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        login_email = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        login_pass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        error_lbl = new javax.swing.JLabel();
        pass_check = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        StudentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PresentCourse = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Results = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        FeesWaivers = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        routine = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        student_notice = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        TeacherPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PresentCourse2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        AddResult = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        attendance = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        routine1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        notice = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        AddStudentPanel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        AddTeacherPanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        UpdatelDataPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        update_notice = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar_panel.setBackground(new java.awt.Color(0, 153, 153));
        sidebar_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_panelMouseClicked(evt);
            }
        });
        sidebar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        sidebar_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        sidebar_admin.setBackground(new java.awt.Color(0, 153, 153));
        sidebar_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_adminMouseClicked(evt);
            }
        });
        sidebar_admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admin.png"))); // NOI18N
        sidebar_admin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Admin");
        sidebar_admin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 20));

        sidebar_panel.add(sidebar_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 40));

        sidebar_student.setBackground(new java.awt.Color(0, 153, 153));
        sidebar_student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_studentMouseClicked(evt);
            }
        });
        sidebar_student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/graduated.png"))); // NOI18N
        sidebar_student.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Student");
        sidebar_student.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 20));

        sidebar_panel.add(sidebar_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 40));

        sidebar_teacher.setBackground(new java.awt.Color(0, 153, 153));
        sidebar_teacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidebar_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidebar_teacherMouseClicked(evt);
            }
        });
        sidebar_teacher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/teaching.png"))); // NOI18N
        sidebar_teacher.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Teacher");
        sidebar_teacher.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 20));

        sidebar_panel.add(sidebar_teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("  Copyright @ Mashiur Ahmed Hridoy");
        sidebar_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 494, 210, 20));

        jPanel1.add(sidebar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 210, 540));

        centrePanel.setLayout(new java.awt.CardLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cover.png"))); // NOI18N

        javax.swing.GroupLayout coverLayout = new javax.swing.GroupLayout(cover);
        cover.setLayout(coverLayout);
        coverLayout.setHorizontalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverLayout.createSequentialGroup()
                .addComponent(jLabel45)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        coverLayout.setVerticalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverLayout.createSequentialGroup()
                .addComponent(jLabel45)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        centrePanel.add(cover, "card7");

        SignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signup_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SignUp.add(signup_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 171, 249, 39));

        signup_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signup_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SignUp.add(signup_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 249, 39));

        signup_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signup_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SignUp.add(signup_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 250, 40));

        signup_birth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_birth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signup_birth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SignUp.add(signup_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 379, 249, 39));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 445, 189, 40));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 204, 255));
        jLabel34.setText("Login");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        SignUp.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        signup_pass_check.setBackground(new java.awt.Color(255, 255, 255));
        signup_pass_check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        signup_pass_check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_pass_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_pass_checkActionPerformed(evt);
            }
        });
        SignUp.add(signup_pass_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 20, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/signup.png"))); // NOI18N
        SignUp.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        centrePanel.add(SignUp, "card6");

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        login_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        login_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_emailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(login_email, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Login.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 290, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        login_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        login_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_passFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(login_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        Login.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 290, 50));

        login.setBackground(new java.awt.Color(102, 102, 255));
        login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login.setText("LOGIN");
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        Login.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 190, 40));

        error_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error_lbl.setForeground(new java.awt.Color(255, 0, 0));
        error_lbl.setText("[ X ] Incorrect Email or Password");
        Login.add(error_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        pass_check.setBackground(new java.awt.Color(255, 255, 255));
        pass_check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass_check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pass_check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pass_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_checkActionPerformed(evt);
            }
        });
        Login.add(pass_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 20, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sign_in.png"))); // NOI18N
        Login.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 540));

        centrePanel.add(Login, "card5");

        StudentPanel.setBackground(new java.awt.Color(0, 32, 63));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(173, 239, 209));
        jLabel11.setText("Student Section");

        PresentCourse.setBackground(new java.awt.Color(173, 239, 209));
        PresentCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PresentCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Present-course.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 32, 63));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Present Courses");

        javax.swing.GroupLayout PresentCourseLayout = new javax.swing.GroupLayout(PresentCourse);
        PresentCourse.setLayout(PresentCourseLayout);
        PresentCourseLayout.setHorizontalGroup(
            PresentCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PresentCourseLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(24, 24, 24))
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PresentCourseLayout.setVerticalGroup(
            PresentCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PresentCourseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Results.setBackground(new java.awt.Color(173, 239, 209));
        Results.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Results.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/results.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 32, 63));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Results");

        javax.swing.GroupLayout ResultsLayout = new javax.swing.GroupLayout(Results);
        Results.setLayout(ResultsLayout);
        ResultsLayout.setHorizontalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ResultsLayout.setVerticalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FeesWaivers.setBackground(new java.awt.Color(173, 239, 209));
        FeesWaivers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        FeesWaivers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fees-waivers.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 32, 63));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Fees & Waiver");

        javax.swing.GroupLayout FeesWaiversLayout = new javax.swing.GroupLayout(FeesWaivers);
        FeesWaivers.setLayout(FeesWaiversLayout);
        FeesWaiversLayout.setHorizontalGroup(
            FeesWaiversLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeesWaiversLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        FeesWaiversLayout.setVerticalGroup(
            FeesWaiversLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeesWaiversLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(3, 3, 3)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        routine.setBackground(new java.awt.Color(173, 239, 209));
        routine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        routine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/routine.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 32, 63));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Routine");

        javax.swing.GroupLayout routineLayout = new javax.swing.GroupLayout(routine);
        routine.setLayout(routineLayout);
        routineLayout.setHorizontalGroup(
            routineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(routineLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        routineLayout.setVerticalGroup(
            routineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap())
        );

        student_notice.setBackground(new java.awt.Color(173, 239, 209));
        student_notice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        student_notice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/notice.png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 32, 63));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Notice");

        javax.swing.GroupLayout student_noticeLayout = new javax.swing.GroupLayout(student_notice);
        student_notice.setLayout(student_noticeLayout);
        student_noticeLayout.setHorizontalGroup(
            student_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(student_noticeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        student_noticeLayout.setVerticalGroup(
            student_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_noticeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addContainerGap())
        );

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(270, 270, 270))
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPanelLayout.createSequentialGroup()
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentPanelLayout.createSequentialGroup()
                                .addComponent(routine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(student_notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentPanelLayout.createSequentialGroup()
                                .addComponent(PresentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addComponent(FeesWaivers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FeesWaivers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PresentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(routine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        centrePanel.add(StudentPanel, "card2");

        TeacherPanel.setBackground(new java.awt.Color(117, 81, 57));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(242, 237, 215));
        jLabel18.setText("Teacher Section");

        PresentCourse2.setBackground(new java.awt.Color(242, 237, 215));
        PresentCourse2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PresentCourse2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Present-course.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(117, 81, 57));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Present Courses");

        javax.swing.GroupLayout PresentCourse2Layout = new javax.swing.GroupLayout(PresentCourse2);
        PresentCourse2.setLayout(PresentCourse2Layout);
        PresentCourse2Layout.setHorizontalGroup(
            PresentCourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PresentCourse2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(24, 24, 24))
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PresentCourse2Layout.setVerticalGroup(
            PresentCourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PresentCourse2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddResult.setBackground(new java.awt.Color(242, 237, 215));
        AddResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        AddResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/results.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(117, 81, 57));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Add Results");

        javax.swing.GroupLayout AddResultLayout = new javax.swing.GroupLayout(AddResult);
        AddResult.setLayout(AddResultLayout);
        AddResultLayout.setHorizontalGroup(
            AddResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddResultLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel23)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        AddResultLayout.setVerticalGroup(
            AddResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(3, 3, 3)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        attendance.setBackground(new java.awt.Color(242, 237, 215));
        attendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        attendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/attendance.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(117, 81, 57));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Attendance");

        javax.swing.GroupLayout attendanceLayout = new javax.swing.GroupLayout(attendance);
        attendance.setLayout(attendanceLayout);
        attendanceLayout.setHorizontalGroup(
            attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
            .addGroup(attendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        attendanceLayout.setVerticalGroup(
            attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        routine1.setBackground(new java.awt.Color(242, 237, 215));
        routine1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        routine1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/routine.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(117, 81, 57));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Routine");

        javax.swing.GroupLayout routine1Layout = new javax.swing.GroupLayout(routine1);
        routine1.setLayout(routine1Layout);
        routine1Layout.setHorizontalGroup(
            routine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(routine1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        routine1Layout.setVerticalGroup(
            routine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routine1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addContainerGap())
        );

        notice.setBackground(new java.awt.Color(242, 237, 215));
        notice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        notice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/notice.png"))); // NOI18N

        jLabel40.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(117, 81, 57));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Notice");

        javax.swing.GroupLayout noticeLayout = new javax.swing.GroupLayout(notice);
        notice.setLayout(noticeLayout);
        noticeLayout.setHorizontalGroup(
            noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addGroup(noticeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noticeLayout.setVerticalGroup(
            noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noticeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addContainerGap())
        );

        javax.swing.GroupLayout TeacherPanelLayout = new javax.swing.GroupLayout(TeacherPanel);
        TeacherPanel.setLayout(TeacherPanelLayout);
        TeacherPanelLayout.setHorizontalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(265, 265, 265))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherPanelLayout.createSequentialGroup()
                        .addComponent(routine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TeacherPanelLayout.createSequentialGroup()
                        .addComponent(PresentCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118)
                .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        TeacherPanelLayout.setVerticalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TeacherPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PresentCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(routine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        centrePanel.add(TeacherPanel, "card3");

        AdminPanel.setBackground(new java.awt.Color(46, 82, 102));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(211, 208, 203));
        jLabel27.setText("Admin Section");

        AddStudentPanel.setBackground(new java.awt.Color(211, 208, 203));
        AddStudentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        AddStudentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(46, 82, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Add Student");

        javax.swing.GroupLayout AddStudentPanelLayout = new javax.swing.GroupLayout(AddStudentPanel);
        AddStudentPanel.setLayout(AddStudentPanelLayout);
        AddStudentPanelLayout.setHorizontalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddStudentPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(24, 24, 24))
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddStudentPanelLayout.setVerticalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddTeacherPanel.setBackground(new java.awt.Color(211, 208, 203));
        AddTeacherPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        AddTeacherPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-teacher.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(46, 82, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Add Teacher");

        javax.swing.GroupLayout AddTeacherPanelLayout = new javax.swing.GroupLayout(AddTeacherPanel);
        AddTeacherPanel.setLayout(AddTeacherPanelLayout);
        AddTeacherPanelLayout.setHorizontalGroup(
            AddTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddTeacherPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(24, 24, 24))
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddTeacherPanelLayout.setVerticalGroup(
            AddTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTeacherPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UpdatelDataPanel.setBackground(new java.awt.Color(211, 208, 203));
        UpdatelDataPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        UpdatelDataPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update-data.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(46, 82, 102));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Update Data");

        javax.swing.GroupLayout UpdatelDataPanelLayout = new javax.swing.GroupLayout(UpdatelDataPanel);
        UpdatelDataPanel.setLayout(UpdatelDataPanelLayout);
        UpdatelDataPanelLayout.setHorizontalGroup(
            UpdatelDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatelDataPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(24, 24, 24))
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdatelDataPanelLayout.setVerticalGroup(
            UpdatelDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatelDataPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        update_notice.setBackground(new java.awt.Color(211, 208, 203));
        update_notice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        update_notice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/notice.png"))); // NOI18N

        jLabel44.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(46, 82, 102));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Update Notice");

        javax.swing.GroupLayout update_noticeLayout = new javax.swing.GroupLayout(update_notice);
        update_notice.setLayout(update_noticeLayout);
        update_noticeLayout.setHorizontalGroup(
            update_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_noticeLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(24, 24, 24))
            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        update_noticeLayout.setVerticalGroup(
            update_noticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_noticeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(278, 278, 278))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(AdminPanelLayout.createSequentialGroup()
                            .addComponent(AddStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)
                            .addComponent(AddTeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdatelDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UpdatelDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddTeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89)
                .addComponent(update_notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        centrePanel.add(AdminPanel, "card4");

        jPanel1.add(centrePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 85, 790, 540));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 95, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/University-Portal-Top.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 625));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int x=210;
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if(x==210)
        {
            sidebar_panel.setSize(210,540);
            Thread th = new Thread()
            {
                public void run()
                {
                    try{
                        for(int i=210;i>=0;i--)
                        {
                            Thread.sleep(1);
                            sidebar_panel.setSize(i,540);
                        }
                    } catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(x == 0)
        {
            sidebar_panel.show();
            sidebar_panel.setSize(x, 540);
            Thread th =new Thread()
            {
                public void run()
                {
                    try
                    {
                        for(int i=0;i<=x;i++)
                        {
                            Thread.sleep(1);
                            sidebar_panel.setSize(i,540);
                        }
                    } catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=210;
        }
    }//GEN-LAST:event_jLabel3MouseClicked
int i=1,j=1,k=1;
    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
//        labelcolor(jLabel2);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
//        resetlabelcolor(jLabel2);
    }//GEN-LAST:event_jLabel3MouseEntered
String s;
    private void sidebar_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_adminMouseClicked
        // TODO add your handling code here:
        onClick(sidebar_admin);
        onLeaveClick(sidebar_student);
        onLeaveClick(sidebar_teacher);
        s="admin";
        if(i==1)
        {
            SignUp.setVisible(false);
            Login.setVisible(true);
            TeacherPanel.setVisible(false);
            StudentPanel.setVisible(false);
            AdminPanel.setVisible(false);
            cover.setVisible(false);
        }
        else
        {
        AdminPanel.setVisible(true);
        Login.setVisible(false);
        SignUp.setVisible(false);
        TeacherPanel.setVisible(false);
        StudentPanel.setVisible(false);
        cover.setVisible(false);
        }

    }//GEN-LAST:event_sidebar_adminMouseClicked

    private void sidebar_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_studentMouseClicked
        // TODO add your handling code here:
        onLeaveClick(sidebar_admin);
        onClick(sidebar_student);
        onLeaveClick(sidebar_teacher);
        s="student";
        if(j==1)
        {
            
            SignUp.setVisible(true);
            Login.setVisible(false);
            TeacherPanel.setVisible(false);
            StudentPanel.setVisible(false);
            AdminPanel.setVisible(false);
            cover.setVisible(false);
        }
        else
        {
            SignUp.setVisible(false);
            Login.setVisible(false);
            TeacherPanel.setVisible(false);
            StudentPanel.setVisible(true);
            AdminPanel.setVisible(false);
            cover.setVisible(false);
        }

    }//GEN-LAST:event_sidebar_studentMouseClicked

    private void sidebar_teacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_teacherMouseClicked
        // TODO add your handling code here:
        onLeaveClick(sidebar_admin);
        onLeaveClick(sidebar_student);
        onClick(sidebar_teacher);
        s="teacher";
        
        if(k==1)
        { 
            SignUp.setVisible(true);
            Login.setVisible(false);
            TeacherPanel.setVisible(false);
            StudentPanel.setVisible(false);
            AdminPanel.setVisible(false);
            cover.setVisible(false);
        }
        else
        {
        Login.setVisible(false);
        SignUp.setVisible(false);
        TeacherPanel.setVisible(true);
        StudentPanel.setVisible(false);
        AdminPanel.setVisible(false);
        cover.setVisible(false);
        }

    }//GEN-LAST:event_sidebar_teacherMouseClicked

    private void pass_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_checkActionPerformed
        // TODO add your handling code here:
        if(pass_check.isSelected())
        {
            login_pass.setEchoChar((char)0);
        }
        else
        {
            login_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_pass_checkActionPerformed

    private void login_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_emailFocusGained
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(login_email.getText().equals("hridoy@gmail.com"))
        {
            login_email.setText("");
            login_email.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_login_emailFocusGained

    private void login_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_emailFocusLost
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(login_email.getText().equals(""))
        {
            login_email.setText("hridoy@gmail.com");
            login_email.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_login_emailFocusLost

    private void login_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passFocusGained
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(login_pass.getText().equals("hridoy"))
        {
            login_pass.setText("");
            login_pass.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_login_passFocusGained

    private void login_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passFocusLost
        // TODO add your handling code here:
        error_lbl.setVisible(false);
        if(login_pass.getText().equals(""))
        {
            login_pass.setText("hridoy");
            login_pass.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_login_passFocusLost

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
//        Connection con=MyConnection.getConnection();
//            PreparedStatement ps;
//            
//            try
//            {
//                ps=con.prepareStatement("SELECT * FROM user WHERE mail=? AND password=MD5(?)");
//                ps.setString(1, login_email.getText());
//                ps.setString(2, String.valueOf(login_pass.getPassword()));
//                ResultSet rs = ps.executeQuery();
//                
//                if(rs.next())
//                {
//                    Front_page front=new Front_page();
//                    front.setVisible(true);
//                    front.pack();
//                    front.setLocationRelativeTo(null);
//                    this.dispose();
                    
//                                if(s=="admin")
//            {
//        StudentPanel.setVisible(false);
//        SignUp.setVisible(false);
//        Login.setVisible(false);
//        TeacherPanel.setVisible(false);
//        AdminPanel.setVisible(true);
//        i++;
//            }
//            if(s=="student")
//            {
//        StudentPanel.setVisible(true);
//        SignUp.setVisible(false);
//        Login.setVisible(false);
//        TeacherPanel.setVisible(false);
//        AdminPanel.setVisible(false);
//        j++;
//            }
//            if(s=="teacher")
//            {
//        StudentPanel.setVisible(false);
//        SignUp.setVisible(false);
//        Login.setVisible(false);
//        TeacherPanel.setVisible(true);
//        AdminPanel.setVisible(false);
//        k++;
//            }
//                    
//                }
//                else
//                {
//                     JOptionPane.showMessageDialog(this, "Username and Password Wrong...");
//
//                }
//                
//            }
//            catch (SQLException ex) {
//
//        }
        
        
        if(login_email.getText().equals("hridoy@gmail.com") && login_pass.getText().equals("hridoy"))
        {
            if(s=="admin")
            {
        StudentPanel.setVisible(false);
        SignUp.setVisible(false);
        Login.setVisible(false);
        TeacherPanel.setVisible(false);
        AdminPanel.setVisible(true);
        i++;
            }
            if(s=="student")
            {
        StudentPanel.setVisible(true);
        SignUp.setVisible(false);
        Login.setVisible(false);
        TeacherPanel.setVisible(false);
        AdminPanel.setVisible(false);
        j++;
            }
            if(s=="teacher")
            {
        StudentPanel.setVisible(false);
        SignUp.setVisible(false);
        Login.setVisible(false);
        TeacherPanel.setVisible(true);
        AdminPanel.setVisible(false);
        k++;
            }
        }
        else
            error_lbl.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        Login.setVisible(true);
        SignUp.setVisible(false);
        TeacherPanel.setVisible(false);
        StudentPanel.setVisible(false);
        AdminPanel.setVisible(false);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void signup_pass_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_pass_checkActionPerformed
        // TODO add your handling code here:
        if(signup_pass_check.isSelected())
        {
            signup_pass.setEchoChar((char)0);
        }
        else
        {
            signup_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_signup_pass_checkActionPerformed

    private void sidebar_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebar_panelMouseClicked
        // TODO add your handling code here:
        cover.setVisible(true);
        onLeaveClick(sidebar_admin);
        onLeaveClick(sidebar_student);
        onLeaveClick(sidebar_teacher);
    }//GEN-LAST:event_sidebar_panelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddResult;
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JPanel AddTeacherPanel;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel FeesWaivers;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel PresentCourse;
    private javax.swing.JPanel PresentCourse2;
    private javax.swing.JPanel Results;
    private javax.swing.JPanel SignUp;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JPanel TeacherPanel;
    private javax.swing.JPanel UpdatelDataPanel;
    private javax.swing.JPanel attendance;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JPanel cover;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton login;
    private javax.swing.JTextField login_email;
    private javax.swing.JPasswordField login_pass;
    private javax.swing.JPanel notice;
    private javax.swing.JCheckBox pass_check;
    private javax.swing.JPanel routine;
    private javax.swing.JPanel routine1;
    private javax.swing.JPanel sidebar_admin;
    private javax.swing.JPanel sidebar_panel;
    private javax.swing.JPanel sidebar_student;
    private javax.swing.JPanel sidebar_teacher;
    private javax.swing.JTextField signup_birth;
    private javax.swing.JTextField signup_email;
    private javax.swing.JTextField signup_name;
    private javax.swing.JPasswordField signup_pass;
    private javax.swing.JCheckBox signup_pass_check;
    private javax.swing.JPanel student_notice;
    private javax.swing.JPanel update_notice;
    // End of variables declaration//GEN-END:variables
//    private void labelcolor(JLabel label)
//    {
//        label.setBackground(new java.awt.Color(53,162,107));
//    }
//        private void resetlabelcolor(JLabel label)
//    {
//        label.setBackground(new java.awt.Color(54,70,78));
//    }

}
